### PR TITLE
Replace deprecated DNS library calls (requires dnspython >= 2.0.0)

### PR DESCRIPTION
**Pull request by kinkie**
dns.resolver.query() is deprecated and issues noisy warnings.
Replace it with dns.resolver.resolve()

### CODE REVIEW

**Comment by Trim** [comment]
Thanks for the request. This warning is now several years old, that's a good time to upgrade the code.

I'll take time this week to merge your patch and release a new major version of acme-dns-tiny.

**Comment by Trim** [comment]
As I'll release it as a new major version, I think I'll leave the `search` option to `None` and documents this behavior change in the new version (we won't use anymore [`the search list configured in the system’s resolver configuration`](https://dnspython.readthedocs.io/en/stable/resolver-class.html#dns.resolver.Resolver.use_search_by_default)).

Indeed, the challenge will be checked by an external DNS client and this ones doesn't know anything about the `acme-dns-tiny` system resolver configuration. Does that sound right?

**Comment by kinkie** [comment]
That's a fair point.
In practice, it won't (or shouldn't) make any difference, as all names in
the cert are fully qualified.

I can't see any obvious place in acme_dns_tiny where unqualified names are
discarded, but I would expect Let's Encrypt to do that. Would it maybe make
sense to add this to the code in order to have a more meaningful error
message?

But I agree that preempting the search list is in practice the most
sensible behaviour in this context.

**Comment by Trim** [comment]
Thanks again for the patch, it has been merged as commit b88ae03782e3811d128153530987b8f947edaee9 (I've just modified the commit message to emphasis the breaking change).

It took more time to release than I expected, because I took the opportunity to rework the project website and write a [release announce for the version 4.0](https://acme-dns-tiny.adorsaz.ch/articles/release-v4.0.html).

Thanks for your patience :)

**Comment by kinkie** [comment]
> Thanks again for the patch, it has been merged as commit [b88ae03](https://github.com/Trim/acme-dns-tiny/commit/b88ae03782e3811d128153530987b8f947edaee9) (I've just modified the commit message to emphasis the breaking change).
> 
> It took more time to release than I expected, because I took the opportunity to rework the project website and write a [release announce for the version 4.0](https://acme-dns-tiny.adorsaz.ch/articles/release-v4.0.html).
> 
> Thanks for your patience :)

Thanks for writing this software, it works very well for me.
Let me know if there is anything I can do to help

**Pull request closed without merging**
